apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nathyguaillas/fintech-backend:v2
          ports:
            - containerPort: 3001
              name: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3001"
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: fintech_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fintech-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fintech-db-secret
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fintech
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
